spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lhz783009838/spring-cloud-study
          search-paths: config-package
          username: lhz783009838
          password: lhz13860798521
server:
  port: 1120
