spring:
  application:
    name: microservice-consumer-movie-ribbon

server:
  port: 1115
eureka:
  client:
    serviceUrl:
     defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    prefer-ip-address: true

