spring:
  application:
    name: microsevice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

server:
  port: 1113

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    #healthcheck: # 开启健康检查
      #enabled: true
  instance:
    preferIpAddress: true
    #lease-expiration-duration-in-seconds: 30 # 续约到期时间
    #lease-renewal-interval-in-seconds: 10 #续约更新时间
