spring:
  application:
    name: microsevice-discover-eureka

server:
  port: 1112                 # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: peer2
    #preferIpAddress: true # 指定该Eureka实例的主机名

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
  #server:
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 4000