spring:
  application:
    name: microsevice-discover-eureka

server:
  port: 1111 # 指定该Eureka实例的端口

eureka:
  #server:
    #enable-self-preservation: false #关闭自我保护模式
  instance:
    hostname: peer1 # 指定该Eureka实例的主机名
    #preferIpAddress: true
  client:
    fetchRegistry: true  #是否检索服务，维护服务实例，不需要检索
    registerWithEureka: true  #是否向注册中心注册，由自己是注册中心，所以不向注册中心注册自己
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/

